import 'package:flutter/material.dart';
import 'package:tech_31/src/feature/dashboard/model/category_model.dart';
import 'package:tech_31/src/feature/dashboard/model/driver_model.dart';
import 'package:tech_31/src/feature/dashboard/model/statistic_model.dart';

class AppConst {
  static List<CategoryModel> categoryList = [
    CategoryModel(
        img: "assets/icons/Accepted.png", onTap: () {}, titile: "Accepted"),
    CategoryModel(
        img: "assets/icons/OnAction.png", onTap: () {}, titile: "On Action"),
    CategoryModel(
        img: "assets/icons/Deliverd.png", onTap: () {}, titile: "Delivered"),
    CategoryModel(
        img: "assets/icons/RATES.png", onTap: () {}, titile: "Reviews"),
  ];

  static List<Driver> driver = [
    Driver(
        name: "Mohammad Avsar",
        driverImg: "assets/img/Mohammad Avsar.jpg",
        location: "Amman-University st   ",
        carType: "Hyundai Ionic - 2023",
        acceptedAt: "1:45",
        acceptedBy: "Admin:Mohammad   ",
        action: ["Accepted", "OnAction"],
        driverNumber: "+962-969-6274",
        orderAt: "2:00 PM",
        orderBy: "Khaled Salem",
        orderNumber: "+962-985-2451",
        rideDtart: Img(title: "assets/img/Fuel.jpg", time: "2:21"),
        rideEnd: null,
        wentAt: "2:21 PM",
        wentTo: "Amman Dabouq"),
    Driver(
        name: "Wael Mohsen",
        driverImg: "assets/img/Wael Mohsen.jpg",
        location: "Amman-Dabouq   ",
        carType: " Toyota Prius - 2012",
        acceptedAt: "1:45",
        acceptedBy: "Admin:Mohammad",
        action: ["Accepted", "OnAction"],
        driverNumber: "+962-969-6274",
        orderAt: "2:00 PM",
        orderBy: "Khaled Salem",
        orderNumber: "+962-985-2451",
        rideDtart: Img(title: "assets/img/Fuel.jpg", time: "2:21"),
        rideEnd: null,
        wentAt: "2:21 PM",
        wentTo: "Amman Dabouq"),
    Driver(
        name: "Salem Mohammad",
        driverImg: "assets/img/Salem Mohammad.jpg",
        location: "Amman-Al-Madina Circle   ",
        carType: " Kia spectra - 2001",
        acceptedAt: "1:45",
        acceptedBy: "Admin:Mohammad",
        action: ["Accepted", "OnAction"],
        driverNumber: "+962-969-6274",
        orderAt: "2:00 PM",
        orderBy: "Khaled Salem",
        orderNumber: "+962-985-2451",
        rideDtart: Img(title: "assets/img/Fuel.jpg", time: "2:21"),
        rideEnd: null,
        wentAt: "2:21 PM",
        wentTo: "Amman Dabouq"),
    Driver(
        name: "Mohammad Avsar",
        driverImg: "assets/img/Mohammad Avsar.jpg",
        location: "Amman-University st   ",
        carType: "Hyundai Ionic - 2023",
        acceptedAt: "1:45",
        acceptedBy: "Admin:Mohammad",
        action: ["Accepted", "OnAction"],
        driverNumber: "+962-969-6274",
        orderAt: "2:00 PM",
        orderBy: "Khaled Salem",
        orderNumber: "+962-985-2451",
        rideDtart: Img(title: "assets/img/Fuel.jpg", time: "2:21"),
        rideEnd: null,
        wentAt: "2:21 PM",
        wentTo: "Amman Dabouq"),
    Driver(
        name: "Wael Mohsen",
        driverImg: "assets/img/Wael Mohsen.jpg",
        location: "Amman-Dabouq   ",
        carType: " Toyota Prius - 2012",
        acceptedAt: "1:45",
        acceptedBy: "Admin:Mohammad",
        action: ["Accepted", "OnAction"],
        driverNumber: "+962-969-6274",
        orderAt: "2:00 PM",
        orderBy: "Khaled Salem",
        orderNumber: "+962-985-2451",
        rideDtart: Img(title: "assets/img/Fuel.jpg", time: "2:21"),
        rideEnd: null,
        wentAt: "2:21 PM",
        wentTo: "Amman Dabouq"),
    Driver(
        name: "Salem Mohammad",
        driverImg: "assets/img/Salem Mohammad.jpg",
        location: "Amman-Al-Madina Circle   ",
        carType: " Kia spectra - 2001",
        acceptedAt: "1:45",
        acceptedBy: "Admin:Mohammad",
        action: ["Accepted", "OnAction"],
        driverNumber: "+962-969-6274",
        orderAt: "2:00 PM",
        orderBy: "Khaled Salem",
        orderNumber: "+962-985-2451",
        rideDtart: Img(title: "assets/img/Fuel.jpg", time: "2:21"),
        rideEnd: null,
        wentAt: "2:21 PM",
        wentTo: "Amman Dabouq"),
    Driver(
        name: "Mohammad Avsar",
        driverImg: "assets/img/Mohammad Avsar.jpg",
        location: "Amman-University St   ",
        carType: "Hyundai Ioniq - 2023",
        acceptedAt: "1:45",
        acceptedBy: "Admin:Mohammad",
        action: ["Accepted", "OnAction"],
        driverNumber: "+962-969-6274",
        orderAt: "2:00 PM",
        orderBy: "Khaled Salem",
        orderNumber: "+962-985-2451",
        rideDtart: Img(title: "assets/img/Fuel.jpg", time: "2:21"),
        rideEnd: null,
        wentAt: "2:21 PM",
        wentTo: "Amman Dabouq"),
  ];
  static List<Statistic> statistic = [
    Statistic(
        title: "Rides",
        icons: Icons.directions_car_filled,
        statistic: "58",
        subTitle: " All Delivered Rides Today",
        secTitle: "Ride"),
    Statistic(
        title: "Most Ordered Area",
        icons: Icons.location_on_sharp,
        statistic: "22%",
        subTitle: " Amman- Jabal Al-Hussain",
        secTitle: ""),
    Statistic(
        title: "Incidents/Accidents",
        icons: Icons.minor_crash_outlined,
        statistic: "1",
        subTitle: "Incidents/Accidents that happened today",
        secTitle: "Accidents"),
    Statistic(
        title: "Active Drivers",
        icons: Icons.directions_car_filled,
        statistic: "25",
        subTitle: " Active Drivers Now",
        secTitle: "Drivers"),
  ];
}
